http:
  routers:
    router1:
      rule: "Host(`localhost`)"
      service: service1
      middlewares:
        - example

  middlewares:
    example:
      luascript:
        script: middleware.lua

  services:
    service1:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:2000"